import { Injectable, Logger } from '@nestjs/common';
import * as ffmpeg from 'fluent-ffmpeg';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';

export interface RenderInput {
  /** Path to the base avatar video/loop (talking-head clip or static portrait) */
  avatarClipPath: string;
  /** Path to the narration audio generated by the TTS/avatar provider */
  narrationAudioPath: string;
  /** Optional burned-in subtitle (.srt) file */
  subtitlesPath?: string;
  resolution: '1280x720' | '1920x1080' | '3840x2160';
}

@Injectable()
export class FfmpegService {
  private readonly logger = new Logger(FfmpegService.name);

  async renderVideo(input: RenderInput): Promise<string> {
    const outputPath = path.join(
      os.tmpdir(),
      `narrator-${Date.now()}-${Math.random().toString(36).slice(2)}.mp4`,
    );

    await new Promise<void>((resolve, reject) => {
      const command = ffmpeg()
        .input(input.avatarClipPath)
        .input(input.narrationAudioPath)
        .outputOptions([
          '-c:v libx264',
          '-c:a aac',
          '-shortest',
          `-s ${input.resolution}`,
          '-pix_fmt yuv420p',
        ]);

      if (input.subtitlesPath && fs.existsSync(input.subtitlesPath)) {
        command.videoFilters(`subtitles=${input.subtitlesPath}`);
      }

      command
        .on('start', (cmd) => this.logger.debug(`ffmpeg start: ${cmd}`))
        .on('error', (err) => reject(err))
        .on('end', () => resolve())
        .save(outputPath);
    });

    return outputPath;
  }
}
